#! /bin/bash

PARTICIPATION_SCORES=( )
  # The participation score can't be provided till the end of the semester
  # Via self-evaluation, you can define a value above. 
  # 
  # For example, if you believe you are slight above average in 
  #    1. attending class,
  #    1. asking questions, etc., in class,
  #    1. participating in Slack communications,
  #    1. providing feedback by the feedback system,
  #    1. turn in your assignments in on time,
  #    1. etc., 
  #
  # You could associate a score of 78% for your participation.
  # 
  #    PARTICIPATION_SCORE=( 78 )

# Syllabus Breakdown
PARTICIPATION_WEIGHT=0.15
LABORATORY_WEIGHT=0.40
QUIZ_WEIGHT=0.15
EXAM_WEIGHT=0.30


#####################################################################

dir_name=$(basename $(pwd) )
if [[ dir_name == 'deliverables' ]] ; then
  echo "You need to run this program from the 'deliverables' directory."
  exit 1
fi

function average () {

  value=0
  if (( $# == 0 )) ; then
    echo "0"
  else
    for ((i=1; i <= $#; i++)) ; do
      (( value += $(eval echo "\${${i}}") )) 
    done
    echo "$(( value / ( i - 1 ) ))"
  fi
}

# Algorithm:
#   1. source the default grades for deliverables that have not been assigned
#   1. source all the available "grade.report"s
#   1. collect individual scores into category scores
#      1. Participation Scores:
#         * we anticipate there will be no participation scores
#         * skip this step if the student provided a "guess"
#      1. Laboratory Scores:
#         * Section 1:  ASSIGNMENT_1[0-9]_total
#         * Section 2:  ASSIGNMENT_2[0-9]_total
#         * Section 3:  ASSIGNMENT_3[0-9]_total
#         * Section 4:  ASSIGNMENT_4[0-9]_total
#      1. Quiz Scores:
#         * Section 1:  ASSIGNMENT_10_total
#         * Section 2:  ASSIGNMENT_30_total
#      1. Exam Scores:
#         * Section 1:  ASSIGNMENT_20_total
#         * Section 2:  ASSIGNMENT_40_total
#   1. Calculate the average for each section
#   1. If Participation Score is undefined,
#      * prompt the user for "guess"
#      * if zero, then assign the value average of the other sections
#   1. Perform a weighted sum of all the sectional scores
#   1. Emit a report 

# Source the default grade assignment
if [[ -f grade_estimator.defaults ]] ; then
  source grade_estimator.defaults
fi

# Source each grade.report
while read _grade_report ; do
    source $_grade_report
done < <( find . -name grade.report -print )



# Collect the Participation Scores
if [[ -z "$PARTICIPATION_SCORES" ]] ; then
  PARTICIPATION_SCORES=( )
   for i in 1 2 3 4 5 6 7 8 9 ; do
     PARTICIPATION_SCORES+=( $( eval echo "\${ASSIGNMENT_0${i}_total}" ) )  
   done
fi

# Collect the Laboratory Scores
LABORATORY_SCORES=( )
   for i in 1 2 3 4 5 6 7 8 9 ; do
     LABORATORY_SCORES+=( $( eval echo "\${ASSIGNMENT_1${i}_total}" ) )
   done
   for i in 1 2 3 4 5 6 7 8 9 ; do
     LABORATORY_SCORES+=( $( eval echo "\${ASSIGNMENT_2${i}_total}" ) )
   done
   for i in 1 2 3 4 5 6 7 8 9 ; do
     LABORATORY_SCORES+=( $( eval echo "\${ASSIGNMENT_3${i}_total}" ) )
   done
   for i in 1 2 3 4 5 6 7 8 9 ; do
     LABORATORY_SCORES+=( $( eval echo "\${ASSIGNMENT_4${i}_total}" ) )
   done


# Collect the Quiz and Exam scores
QUIZ_SCORES=( ${ASSIGNMENT_10_total} ${ASSIGNMENT_30_total} )
EXAM_SCORES=( ${ASSIGNMENT_20_total} ${ASSIGNMENT_40_total} )

# Calculate the Average in each section
LABORATORY_AVERAGE=$(average "${LABORATORY_SCORES[@]}")
QUIZ_AVERAGE=$(average "${QUIZ_SCORES[@]}")
EXAM_AVERAGE=$(average "${EXAM_SCORES[@]}")


# For Participation Average
#   The Prof will be assigning a value for "participation" at the end of the semester
#   Effectively, this value is stored in ASSIGNMENT_00_total
#
# To estimate the final score for this category, then ...
# - if there is a assigned default use it and add it to the PARTICIPATION_SCORES.
# - if the user is prompted for a value use it, and add it to the PARTICIPATION_SCORES
# - otherwise add the average of the Labs, Quiz, Exams, and 

if [[ -n "${ASSIGNMENT_00_total}" ]] ; then 
   # Add the Student's default for Participation into the list of scores
   PARTICIPATION_SCORES=( ${ASSIGNMENT_00_total}  ${PARTICIPATION_SCORES[@]} )
   PARTICIPATION_CALCULATION=default
else
   # Prompt the Student to provide a default value
   echo "Based upon self-evaluation, enter your participation score."
   echo "Skip if you you want your participation score to be equal to the average of your other scores"
   read -p "Participation (0..100): " ASSIGNMENT_00_total
   if (( ${ASSIGNMENT_00_total} != 0 )) ; then 
     PARTICIPATION_SCORES=( ${ASSIGNMENT_00_total} ${PARTICIPATION_SCORES[@]} )
     PARTICIPATION_CALCULATION=prompted
   fi
fi

if (( ${ASSIGNMENT_00_total} == 0 )) ; then 
   # If the value is zero, use the average of the other categories as an estimate
   PARTICIPATION_SCORES=( $( average $LABORATORY_AVERAGE $QUIZ_AVERAGE $EXAM_AVERAGE ) ${PARTICIPATION_SCORES[@]} )
   PARTICIPATION_CALCULATION=averaged
fi


PARTICIPATION_AVERAGE=$(average "${PARTICIPATION_SCORES[@]}")

# Syllabus Breakdown
PARTICIPATION_PERCENT=15
LABORATORY_PERCENT=40
QUIZ_PERCENT=15
EXAM_PERCENT=30

# Individual Calculation (Note integer division, hence some information loss)
PARTICIPATION_GP=$(( PARTICIPATION_AVERAGE * PARTICIPATION_PERCENT / 100 ))
LABORATORY_GP=$(( LABORATORY_AVERAGE * LABORATORY_PERCENT / 100 ))
QUIZ_GP=$(( QUIZ_AVERAGE * QUIZ_PERCENT / 100 ))
EXAM_GP=$(( EXAM_AVERAGE * EXAM_PERCENT / 100 ))


CURRENT_GP=$(( PARTIPICATION_GP + LABORATORY_GP  + QUIZ_GP + EXAM_GP  ))

# Consider making the output .md
cat > "$(date +%b_%d).estimated_grade.md" <<EOF
## Grade Estimation Tool

This tool provides an estimiate of your current grade based upon a snapshot in time.
This estimate is based upon the following information:
   1. a set of user provided defaults (see "grade_estimator.defaults")
   1. the current set of graded deliverables
   1. a "guess" of the student's final participation value, said guess can be either
      * default: a user provided defualt value (see "grade_estimator.defaults")
      * prompted: value provided by the student via a prompt
      * average: the average scores of laboratory assignments, quizzes, and exams


## Current Estimated Grade

* Date Prepared: $(date)
* Caveat: Past performance does not predict future performance. 


|                                              | Average                  | Weight                     |Points            
| :--------------------------------------------| -----------------------: | --------------------------:| ------------------: |
|  Participation ($PARTICIPATION_CALCULATION): | ${EXAM_AVERAGE}          | ${PARTICIPATION_PERCENT}%  | ${PARTICIPATION_GP} |
|  Laboratory Assignments:                     | ${QUIZ_AVERAGE}          | ${LABORATORY_PERCENT}%     | ${LABORATORY_GP}    |
|  Quizzes:                                    | ${LABORATORY_AVERAGE}    | ${QUIZ_PERCENT}%           | ${QUIZ_GP}          |
|  Exams:                                      | ${PARTICIPATION_AVERAGE} | ${EXAM_PERCENT}%           | ${EXAM_GP}          |
|  **Total:**                                  |                          |                            | ${CURRENT_GP}       |

|                                              | Scores                     | Count                       | Average                  |
| :--------------------------------------------| -------------------------: | --------------------------: | -----------------------: |        
|  Participation ($PARTICIPATION_CALCULATION): | ${PARTICIPATION_SCORES[@]} | ${#PARTICIPATION_SCORES[@]} | ${EXAM_AVERAGE}          |        
|  Laboratory Assignments:                     | ${LABORATORY_SCORES[@]}    | ${#LABORATORY_SCORES[@]}    | ${QUIZ_AVERAGE}          |        
|  Quizzes:                                    | ${QUIZ_SCORES[@]}          | ${#QUIZ_SCORES[@]}          | ${LABORATORY_AVERAGE}    |        
|  Exams:                                      | ${EXAM_SCORES[@]}          | ${#EXAM_SCORES[@]}          | ${PARTICIPATION_AVERAGE} |        

A Final Participation Score was provided via a $PARTICIPATION_CALCULATION value.

EOF



open "$(date +%b_%d).estimated_grade.md"

